[package]
name = "threemusket"
version = "0.1.0"
authors = ["theomgxz <sg28r8@gmail.com>"]
edition = "2018"



[dependencies]
warp = "0.2"
parking_lot = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["macros"] }
structopt = "0.3"